export const originalData = [
  {
    date: '2024-01-01',
    product: 'Widget A',
    region: 'North',
    sales: 1000,
    quantity: 50,
  },
  {
    date: '2024-01-02',
    product: 'Widget B',
    region: 'South',
    sales: 1500,
    quantity: 75,
  },
  {
    date: '2024-01-03',
    product: 'Widget C',
    region: 'East',
    sales: 900,
    quantity: 45,
  },
  {
    date: '2024-01-04',
    product: 'Widget D',
    region: 'West',
    sales: 2000,
    quantity: 80,
  },
  {
    date: '2024-01-05',
    product: 'Widget B',
    region: 'North',
    sales: 1100,
    quantity: 55,
  },
  {
    date: '2024-01-06',
    product: 'Widget C',
    region: 'South',
    sales: 1700,
    quantity: 65,
  },
  {
    date: '2024-01-07',
    product: 'Widget A',
    region: 'West',
    sales: 1200,
    quantity: 60,
  },
  {
    date: '2024-01-08',
    product: 'Widget B',
    region: 'East',
    sales: 1300,
    quantity: 70,
  },
  {
    date: '2024-01-09',
    product: 'Widget C',
    region: 'North',
    sales: 1400,
    quantity: 72,
  },
  {
    date: '2024-01-10',
    product: 'Widget A',
    region: 'South',
    sales: 1600,
    quantity: 85,
  },
  {
    date: '2024-01-11',
    product: 'Widget D',
    region: 'North',
    sales: 1800,
    quantity: 90,
  },
  {
    date: '2024-01-12',
    product: 'Widget D',
    region: 'East',
    sales: 1900,
    quantity: 95,
  },
  {
    date: '2024-01-13',
    product: 'Widget B',
    region: 'West',
    sales: 1700,
    quantity: 60,
  },
  {
    date: '2024-01-14',
    product: 'Widget A',
    region: 'North',
    sales: 1100,
    quantity: 50,
  },
  {
    date: '2024-01-15',
    product: 'Widget C',
    region: 'South',
    sales: 2100,
    quantity: 100,
  },
  {
    date: '2024-01-16',
    product: 'Widget D',
    region: 'West',
    sales: 2200,
    quantity: 110,
  },
  {
    date: '2024-01-17',
    product: 'Widget A',
    region: 'East',
    sales: 1300,
    quantity: 70,
  },
  {
    date: '2024-01-18',
    product: 'Widget B',
    region: 'North',
    sales: 1400,
    quantity: 75,
  },
  {
    date: '2024-01-19',
    product: 'Widget C',
    region: 'East',
    sales: 1600,
    quantity: 80,
  },
  {
    date: '2024-01-20',
    product: 'Widget D',
    region: 'South',
    sales: 2000,
    quantity: 90,
  },
];

export const options = {
  rows: [{ uniqueName: 'product', caption: 'Product' }],
  columns: [{ uniqueName: 'region', caption: 'Region' }],
  measures: [
    {
      uniqueName: 'sales',
      caption: 'Total Sales',
      aggregation: 'sum',
      format: {
        type: 'currency',
        currency: 'USD',
        locale: 'en-US',
        decimals: 2,
      },
    },
    {
      uniqueName: 'quantity',
      caption: 'Total Quantity',
      aggregation: 'sum',
      format: {
        type: 'number',
        decimals: 2,
        locale: 'en-US',
      },
    },
  ],
  dimensions: [
    { field: 'product', label: 'Product', type: 'string' },
    { field: 'region', label: 'Region', type: 'string' },
    { field: 'date', label: 'Date', type: 'date' },
    { field: 'sales', label: 'Sales', type: 'number' },
    { field: 'quantity', label: 'Quantity', type: 'number' },
  ],
  defaultAggregation: 'sum',
  isResponsive: true,
  groupConfig: {
    rowFields: ['product'],
    columnFields: ['region'],
    grouper: (item, fields) => fields.map(field => item[field]).join(' - '),
  },
  formatting: {
    sales: {
      type: 'currency',
      currency: 'USD',
      locale: 'en-US',
      decimals: 2,
    },
    quantity: {
      type: 'number',
      decimals: 2,
      locale: 'en-US',
    },
  },
  onRowDragEnd: (fromIndex, toIndex, newData) => {
    console.log('Row dragged:', { fromIndex, toIndex, newData });
  },
  onColumnDragEnd: (fromIndex, toIndex, newColumns) => {
    console.log('Column dragged:', { fromIndex, toIndex, newColumns });
  },
};
